{{- if .Values.mlp.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "mlp.fullname" .}}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.mlp.ingress.class }}
  labels:
    app: {{ include "mlp.name" . }}
    chart: {{ include "mlp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "mlp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.mlp.ingress.host }}
      http:
        paths:
          - path: {{ .Values.mlp.ingress.path | default "/" }}
            backend:
              service:
                name: {{ template "mlp.fullname" .}}
                port: 
                  number: {{ .Values.mlp.service.externalPort }}
{{- end }}
