mlp:
  image:
    pullPolicy: IfNotPresent
    registry: ghcr.io
    repository: gojek/mlp
    tag: v1.5.0
  replicaCount: 1

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi

  livenessProbe:
    path: "/v1/internal/live"
  readinessProbe:
    path: "/v1/internal/ready"
  service:
    externalPort: 8080
    internalPort: 8080
  apiHost: "http://mlp/v1"
  gitlabRedirectUrl: "http://mlp/settings/connected-accounts"
  mlflowTrackingUrl: "http://mlflow.mlp"
  environment: "production"
  encryption:
    # encryption.key must be specified using --set flag.
    key: "example-key-here"
  authorization:
    enabled: false
    serverUrl: http://mlp-authorization-keto
  ingress:
    enabled: false
  teams:
    - marketing
    - operation
    - business
  streams:
    - promotion-marketing
    - operation-strategy
    - business-analyst
  docs:
    [
      {
       "label": "Merlin User Guide",
       "href": "https://github.com/gojek/merlin/blob/main/docs/getting-started/README.md"
      },
      {
       "label": "Turing User Guide",
       "href": "https://github.com/gojek/turing"
      },
      {
       "label": "Feast User Guide",
       "href": "https://docs.feast.dev/user-guide/overview"
      },
    ]
  ui:
    feastCoreApi: "http://feast.dev/v1"
    merlinApi: "http://merlin.dev/v1"
    turingApi: "http://turing.dev/v1"
    clockworkHomepage: "http://clockwork.dev"
    feastHomepage: "http://feast.dev"
    kubeflowHomepage: "http://kubeflow.org"
    merlinHomepage: "http://merlin.dev"
    turingHomepage: "http://turing.dev"

dbMigrations:
  image:
    tag: v4.7.1

gitlab:
  enabled: false
  host: https://gitlab.com
  oauthScopes: read_user
  clientId: #clientId
  clientSecret: #clientSecret

# If you would like to use an external postgres database, you can connect using these credentials
externalPostgres:
  enabled: false
  username: mlp
  database: mlp
  password: password
  address: 127.0.0.1

postgresql:
  enabled: true
  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
  persistence:
    size: 10Gi
  postgresqlUsername: mlp
  postgresqlDatabase: mlp
  # metrics:
  #   enabled: true
  #   serviceMonitor:
  #     enabled: true
  # replication:
  #   enabled: true
  #   user: repl_user
  #   password: repl_password
  #   slaveReplicas: 2
  #   ## Set synchronous commit mode: on, off, remote_apply, remote_write and local
  #   ## ref: https://www.postgresql.org/docs/9.6/runtime-config-wal.html#GUC-WAL-LEVEL
  #   synchronousCommit: "on"
  #   ## From the number of `slaveReplicas` defined above, set the number of those that will have synchronous replication
  #   ## NOTE: It cannot be > slaveReplicas
  #   numSynchronousReplicas: 2
  #   ## Replication Cluster application name. Useful for defining multiple replication policies
  #   applicationName: mlp
